export const magicUserSpells: string[][] = [[
    // 1. Level
    "Charm Person",
    "Detect Magic",
    "Floating Disc",
    "Hold Portal",
    "Light*",
    "Magic Missile",
    "Magic Mouth",
    "Protection from Evil*",
    "Read Languages",
    "Shield",
    "Sleep",
    "Ventriloquism"],
// 2. Level
[
    "Continual Light*",
    "Detect Evil*",
    "Detect Invisible",
    "ESP",
    "Invisibility",
    "Knock",
    "Levitate",
    "Locate Object",
    "Mirror Image",
    "Phantasmal Force",
    "Web",
    "Wizard Lock",
],
// 3. Level
[
    "Clairvoyance",
    "Darkvision",
    "Dispel Magic",
    "Fireball",
    "Fly",
    "Haste*",
    "Hold Person",
    "Invisibility 10‘ radius",
    "Lightning Bolt",
    "Protection from Evil 10’ radius*",
    "Protection from Normal Missiles",
    "Water Breathing",
],
// 4. Level
[
    "Charm Monster",
    "Confusion",
    "Dimension Door",
    "Growth of Plants*",
    "Hallucinatory Terrain",
    "Ice Storm",
    "Massmorph",
    "Polymorph Other",
    "Polymorph Self",
    "Remove Curse*",
    "Wall of Fire",
    "Wizard Eye",
],
// 5. Level
[
    "Animate Dead",
    "Cloudkill",
    "Conjure Elemental",
    "Feeblemind",
    "Hold Monster",
    "Magic Jar",
    "Passwall",
    "Telekinesis",
    "Teleport",
    "Wall of Stone",
],
// 6. Level
[
    "Anti-Magic Shell",
    "Death Spell",
    "Disintegrate",
    "Flesh to Stone*",
    "Geas*",
    "Invisible Stalker",
    "Lower Water",
    "Projected Image",
    "Reincarnate",
    "Wall of Iron",
]
];

export const clericSpells: string[][] = [
    // 1. Level
    [
        "Cure Light Wounds*",
        "Detect Evil*",
        "Detect Magic",
        "Light*",
        "Protection from Evil*",
        "Purify Food and Water",
        "Remove Fear*",
        "Resist Cold",
    ],
    // 2. Level
    [
        "Bless*",
        "Charm Animal",
        "Find Traps",
        "Hold Person",
        "Resist Fire",
        "Silence 15' radius",
        "Speak with Animals",
        "Spiritual Hammer",
    ],
    // 3. Level
    [
        "Continual Light*",
        "Cure Blindness",
        "Cure Disease*",
        "Growth of Animals",
        "Locate Object",
        "Remove Curse*",
        "Speak with Dead",
        "Striking",
    ],
    // 4. Level
    [
        "Animate Dead",
        "Create Water",
        "Cure Serious Wounds*",
        "Dispel Magic",
        "Neutralize Poison*",
        "Protection from Evil 10' radius*",
        "Speak with Plants",
        "Sticks to Snakes",
    ],
    // 5. Level
    [
        "Commune",
        "Create Food",
        "Dispel Evil",
        "Insect Plague",
        "Quest*",
        "Raise Dead*",
        "True Seeing",
        "Wall of Fire",
    ],
    // 6. Level
    [
        "Animate Objects",
        "Blade Barrier",
        "Find the Path",
        "Heal*",
        "Regenerate",
        "Restoration",
        "Speak with Monsters",
        "Word of Recall",
    ],
]